### ISSUE TITLE
Cannot add task 'clean' as a task with that name already exists.

### ISSUE THREAD

**Issue by vibdev** [PeredurOmega/GradleNodePlugin#1]
Awesome plugin, thank you so much for making it.

I am running into an issue getting `Cannot add task 'clean' as a task with that name already exists.` on the `npm {}` block. I suspect it is from [NodeCleanTask.kt](https://github.com/PeredurOmega/GradleNpmPlugin/blob/main/src/main/kotlin/NodeCleanTask.kt) colliding with our project's clean task. 

Is there a way to override the task names provided by the plugin? If not, do you think the plugins internal tasks could be namespaced e.g. `nodeClean`?

We are using GradleNpmPlugin v1.4

**Comment by vibdev** [comment]
oh actually it might be because our package.json has a "clean" script

**Comment by PeredurOmega** [comment]
Thanks ! I am glad you enjoy the plugin !

You encounter this issue because you already have a clean task in your package.json.
By default the plugin creates a task named 'clean' to comply with usual Gradle naming conventions.
I suggest renaming the clean script in your package.json (or removing it as the plugin should handle standard cleaning of the project by itself).
But if you have a specific use case, I could allow for renaming the tasks created by the plugin.

**Comment by marlow-fawn** [comment]
There are cases where the clean task is introduced in files I'm not managing, such as in node_modules. Do you have a suggestion for how to handle this?

**Comment by PeredurOmega** [comment]
Not sure to understand how node_modules files would introduce a clean task as we only use your own package.json to detect create a tasks associated to scripts. Could you elaborate ?
Also now you can use:
`
node {
    cleanTaskName.set("nodeClean")
}
`
This will rename the clean task created by the plugin.
