### ISSUE TITLE
gradle build works but gradle clean build doesn't

### ISSUE THREAD

**Issue by ilovethebeatles** [PeredurOmega/GradleNodePlugin#13]
I run ```gradle build``` in my frontend part of project and it is performed successfully but when I run ```gradle clean build```
it an error occurs:
> react-scripts build
sh: line 1: react-scripts: command not found

Can it be the plugin's bug?

**Comment by PeredurOmega** [comment]
Could you share @ilovethebeatle your package.json (more specifically the scripts part) ?

It could be related to https://stackoverflow.com/questions/47612580/react-scripts-command-not-found

**Comment by ilovethebeatles** [comment]
> Could you share @ilovethebeatle your package.json (more specifically the scripts part) ?
> 
> It could be related to https://stackoverflow.com/questions/47612580/react-scripts-command-not-found

Here it is

  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "lint": "eslint \"src/**/*.{js,jsx}\""
  },

**Comment by PeredurOmega** [comment]
This issue was due to an abnormal dependency on the clean task due to the InputDirectory annotation forcing the dependencies installation. This is now fixed by replacing InputDirectory annotation with Destroys.
Available right now with [2.0.5](https://github.com/PeredurOmega/GradleNodePlugin/releases/tag/2.0.5).
